name: signals_watch_example
description: Example app for signals_watch package

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  signals: ^6.2.0
  signals_watch:
    path: ../

dev_dependencies:

flutter:
  uses-material-design: true
